# Generated by Django 2.0.2 on 2019-08-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0004_auto_20190803_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_colour',
            field=models.CharField(choices=[('To do', 'info'), ('In Progress', 'warning'), ('Complete', 'success')], default='To do', max_length=20),
        ),
    ]
