# Generated by Django 2.0.2 on 2019-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0005_ticket_status_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('dark', 'To do'), ('warning', 'In Progress'), ('success', 'Complete')], default='dark', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status_colour',
            field=models.CharField(choices=[('dark', 'dark'), ('warning', 'warning'), ('success', 'success')], default='dark', max_length=20),
        ),
    ]
