# Generated by Django 2.0.2 on 2019-08-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0006_auto_20190803_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='To do', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status_colour',
            field=models.CharField(choices=[('dark', 'To do'), ('warning', 'In Progress'), ('success', 'Complete')], default='To do', max_length=20),
        ),
    ]
