# Generated by Django 2.0.2 on 2019-08-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0008_auto_20190810_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='contributor',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='voted_by',
            new_name='user',
        ),
    ]
