# Generated by Django 2.0.2 on 2019-08-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0009_auto_20190811_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=5, null=True),
        ),
    ]
